org.gradle.jvmargs=-Xmx4G
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=/Library/Java/JavaVirtualMachines/openjdk-25.jdk/Contents/Home

version=0.0.9
group=earth.terrarium.common_storage_lib

minecraftVersion=26.1.2

modMenuVersion=17.0.0-beta.1
reiVersion=21.11.814

fabricLoaderVersion=0.19.2
fabricApiVersion=0.149.1+26.1.2
