org.gradle.jvmargs=-Xmx4G
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home

enabledPlatforms=fabric,neoforge

version=0.0.8
group=earth.terrarium.common_storage_lib

minecraftVersion=1.21.11
parchmentVersion=2025.07.18

modMenuVersion=17.0.0-beta.1
reiVersion=21.11.814

fabricLoaderVersion=0.18.4
fabricApiVersion=0.141.3+1.21.11

neoforgeVersion=21.11.38-beta
